# Generated by Django 4.1.3 on 2022-11-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("PAID", "Paid")],
                default="Pending",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[("PAYMENT", "Payment"), ("FINE", "Fine")],
                default="Payment",
                max_length=7,
            ),
        ),
    ]
