# Generated by Django 4.1.3 on 2022-11-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_money_to_pay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("PAID", "Paid")], max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[("PAYMENT", "Payment"), ("FINE", "Fine")], max_length=7
            ),
        ),
    ]
