# Generated by Django 4.1.3 on 2022-11-30 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                (
                    "cover",
                    models.CharField(
                        choices=[("H", "HARD"), ("S", "SOFT")], max_length=4
                    ),
                ),
                (
                    "inventory",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ]
                    ),
                ),
                (
                    "daily_fee",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
